# This file was generated by GoReleaser. DO NOT EDIT.
cask "amqp-publish" do
  name "amqp-publish"
  desc "A command-line tool for amqp-publish"
  homepage "https://github.com/yasithab/homebrew-taps"
  version "1.0.7"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "amqp-publish"

  on_macos do
    on_intel do
      url "https://github.com/yasithab/homebrew-taps/releases/download/v#{version}/amqp-publish-#{version}-darwin-amd64.tar.gz",
        verified: "github.com/yasithab/homebrew-taps"
      sha256 "ecfb8d8bfd2d2db02e8dfc681ca411100d6f0b71e081f8af2e69b023ddfaaca3"
    end
    on_arm do
      url "https://github.com/yasithab/homebrew-taps/releases/download/v#{version}/amqp-publish-#{version}-darwin-arm64.tar.gz",
        verified: "github.com/yasithab/homebrew-taps"
      sha256 "67b81f73a91670228fbce3ada730a10cc7a53bf66b42c8a3345f3ef3bcdc116d"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/amqp-publish"]
    end
  end

  # No zap stanza required
end
