# This file was generated by GoReleaser. DO NOT EDIT.
cask "amqp-publish" do
  name "amqp-publish"
  desc "A command-line tool for amqp-publish"
  homepage "https://github.com/yasithab/homebrew-taps"
  version "1.0.11"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "amqp-publish"

  on_macos do
    on_intel do
      url "https://github.com/yasithab/homebrew-taps/releases/download/v#{version}/amqp-publish-#{version}-darwin-amd64.tar.gz",
        verified: "github.com/yasithab/homebrew-taps"
      sha256 "4104e43b14ca236887b293c6bf92f691b5b60e8c2754d135cdc65b727fe94cf7"
    end
    on_arm do
      url "https://github.com/yasithab/homebrew-taps/releases/download/v#{version}/amqp-publish-#{version}-darwin-arm64.tar.gz",
        verified: "github.com/yasithab/homebrew-taps"
      sha256 "56803ddeb6e7fe24e29db88537e13167fb2231a1f6733eb990fce3b95c8b92bf"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/amqp-publish"]
    end
  end

  # No zap stanza required
end
