# This file was generated by GoReleaser. DO NOT EDIT.
cask "amqp-publish" do
  name "amqp-publish"
  desc "A command-line tool for amqp-publish"
  homepage "https://github.com/yasithab/homebrew-taps"
  version "1.0.5"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "amqp-publish"

  on_macos do
    on_intel do
      url "https://github.com/yasithab/homebrew-taps/releases/download/v#{version}/amqp-publish-#{version}-darwin-amd64.tar.gz",
        verified: "github.com/yasithab/homebrew-taps"
      sha256 "e518e38a80dfbd4ce8eba12345a4521062fd23ad744799d335a3eb78ff8a1acd"
    end
    on_arm do
      url "https://github.com/yasithab/homebrew-taps/releases/download/v#{version}/amqp-publish-#{version}-darwin-arm64.tar.gz",
        verified: "github.com/yasithab/homebrew-taps"
      sha256 "6a2dffdc3a965486a37f5dd0cb08377fabbc38433ea8809f292ebaa6326106e4"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/amqp-publish"]
    end
  end

  # No zap stanza required
end
