# This file was generated by GoReleaser. DO NOT EDIT.
cask "bunkr" do
  version "1.0.15"

  on_macos do
    on_intel do
      sha256 "ba6885cdadc4f05351c2329230a590609ba5c7ec3f4fdc794dafa90a3a0536e5"
      url "https://github.com/yasithab/homebrew-taps/releases/download/v#{version}/bunkr-#{version}-darwin-amd64.tar.gz",
        verified: "github.com/yasithab/homebrew-taps"
    end
    on_arm do
      sha256 "620f50da97b53f70876199494961acccb00fa53071f790a2c241d8ef3b4b179e"
      url "https://github.com/yasithab/homebrew-taps/releases/download/v#{version}/bunkr-#{version}-darwin-arm64.tar.gz",
        verified: "github.com/yasithab/homebrew-taps"
    end
  end

  name "bunkr"
  desc "A fast, reliable downloader for Bunkr albums and files"
  homepage "https://github.com/yasithab/homebrew-taps"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bunkr"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bunkr"]
    end
  end

  # No zap stanza required

end
