# This file was generated by GoReleaser. DO NOT EDIT.
cask "bunkr" do
  version "1.0.14"

  on_macos do
    on_intel do
      sha256 "91e35f78728cb4eedabb9e5d20bc91c997b7876e170c91bc5106c3c75100b54b"
      url "https://github.com/yasithab/homebrew-taps/releases/download/v#{version}/bunkr-#{version}-darwin-amd64.tar.gz",
        verified: "github.com/yasithab/homebrew-taps"
    end
    on_arm do
      sha256 "0b30f746aa1ae9301f4aef50882f1aebff12bce20e9dc7d644cef312306626e6"
      url "https://github.com/yasithab/homebrew-taps/releases/download/v#{version}/bunkr-#{version}-darwin-arm64.tar.gz",
        verified: "github.com/yasithab/homebrew-taps"
    end
  end

  name "bunkr"
  desc "A fast, reliable downloader for Bunkr albums and files"
  homepage "https://github.com/yasithab/homebrew-taps"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bunkr"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bunkr"]
    end
  end

  # No zap stanza required

end
