# This file was generated by GoReleaser. DO NOT EDIT.
cask "ssm" do
  name "ssm"
  desc "A command-line tool for AWS SSM"
  homepage "https://github.com/yasithab/homebrew-taps"
  version "1.0.5"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ssm"

  on_macos do
    on_intel do
      url "https://github.com/yasithab/homebrew-taps/releases/download/v#{version}/ssm-#{version}-darwin-amd64.tar.gz",
        verified: "github.com/yasithab/homebrew-taps"
      sha256 "f7d93b976ee4d844660e75ef90927defe063062b03f9fab7fd00d3789313a39c"
    end
    on_arm do
      url "https://github.com/yasithab/homebrew-taps/releases/download/v#{version}/ssm-#{version}-darwin-arm64.tar.gz",
        verified: "github.com/yasithab/homebrew-taps"
      sha256 "0193a7de228dc803040381f567b6e47b200aba26f17de22f3e5809e5a32386ae"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ssm"]
    end
  end

  # No zap stanza required
end
