# This file was generated by GoReleaser. DO NOT EDIT.
cask "ssm" do
  name "ssm"
  desc "A command-line tool for AWS SSM"
  homepage "https://github.com/yasithab/homebrew-taps"
  version "1.0.10"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ssm"

  on_macos do
    on_intel do
      url "https://github.com/yasithab/homebrew-taps/releases/download/v#{version}/ssm-#{version}-darwin-amd64.tar.gz",
        verified: "github.com/yasithab/homebrew-taps"
      sha256 "ad7f6338d5215e8300af1af8a312aea077c3b2c838d934dfdbfed6a2a3d067fe"
    end
    on_arm do
      url "https://github.com/yasithab/homebrew-taps/releases/download/v#{version}/ssm-#{version}-darwin-arm64.tar.gz",
        verified: "github.com/yasithab/homebrew-taps"
      sha256 "e3156cb0d65146ff678a52b29bfc6bba2e7ec82248c0de51cdbe4304cf4a1d71"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ssm"]
    end
  end

  # No zap stanza required
end
