# This file was generated by GoReleaser. DO NOT EDIT.
cask "ssm" do
  name "ssm"
  desc "A command-line tool for AWS SSM"
  homepage "https://github.com/yasithab/homebrew-taps"
  version "1.0.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ssm"

  on_macos do
    on_intel do
      url "https://github.com/yasithab/homebrew-taps/releases/download/v#{version}/ssm-#{version}-darwin-amd64.tar.gz",
        verified: "github.com/yasithab/homebrew-taps"
      sha256 "625caecc64887f1ad2ea68844d0aa4a06b0865638d04a5ab28403c400c270403"
    end
    on_arm do
      url "https://github.com/yasithab/homebrew-taps/releases/download/v#{version}/ssm-#{version}-darwin-arm64.tar.gz",
        verified: "github.com/yasithab/homebrew-taps"
      sha256 "5ee8db27e2fb8b08f437383a273dd97cf1ce31e7929cd49827ad4fc6b932b472"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ssm"]
    end
  end

  # No zap stanza required
end
