# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AmqpPublish < Formula
  desc "Robust RabbitMQ publisher with confirms, retries, and rate limiting"
  homepage "https://github.com/yasithab/homebrew-taps"
  version "1.2.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yasithab/homebrew-taps/releases/download/v1.2.2/amqp-publish-1.2.2-darwin-amd64.tar.gz"
      sha256 "232188bf6572dc7cd21b562f885d63592516ab342d029ec0a27faab552a78bad"

      define_method(:install) do
        bin.install "amqp-publish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yasithab/homebrew-taps/releases/download/v1.2.2/amqp-publish-1.2.2-darwin-arm64.tar.gz"
      sha256 "e7311c14790e10499221fd7ccc2a5d53a8f9e8f4452c304ad3a3a479b8766aaa"

      define_method(:install) do
        bin.install "amqp-publish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yasithab/homebrew-taps/releases/download/v1.2.2/amqp-publish-1.2.2-linux-amd64.tar.gz"
      sha256 "0465f3d3184728e030ccfcfbdbe128e84c109b8f70d782bb33ef130eaf0205d9"
      define_method(:install) do
        bin.install "amqp-publish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yasithab/homebrew-taps/releases/download/v1.2.2/amqp-publish-1.2.2-linux-arm64.tar.gz"
      sha256 "3cea74c293af8a2c7fb37d39fdb1630d281e0276c8ea6888d5f17c454d1d96bc"
      define_method(:install) do
        bin.install "amqp-publish"
      end
    end
  end

  def post_install
    system "/usr/bin/xattr", "-dr", "com.apple.quarantine", bin/"amqp-publish" if OS.mac?
  end

  test do
    system "#{bin}/amqp-publish", "--version"
  end
end
