# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bunkr < Formula
  desc "A fast, reliable downloader for Bunkr albums and files"
  homepage "https://github.com/yasithab/homebrew-taps"
  version "1.2.27"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yasithab/homebrew-taps/releases/download/v1.2.27/bunkr-1.2.27-darwin-amd64.tar.gz"
      sha256 "6bc43161134db68f28e2a4f4423239b39ca0418502a354aa4617f78316993106"

      define_method(:install) do
        bin.install "bunkr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yasithab/homebrew-taps/releases/download/v1.2.27/bunkr-1.2.27-darwin-arm64.tar.gz"
      sha256 "a5c55a92f5824c52bc903da023c4c38633f25aca6a94244ddb0c02b5791a3b2e"

      define_method(:install) do
        bin.install "bunkr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yasithab/homebrew-taps/releases/download/v1.2.27/bunkr-1.2.27-linux-amd64.tar.gz"
      sha256 "ac919265baabd7743ad9eda60f901b5e13cfcad173b3674cf92427437ce0d70d"
      define_method(:install) do
        bin.install "bunkr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yasithab/homebrew-taps/releases/download/v1.2.27/bunkr-1.2.27-linux-arm64.tar.gz"
      sha256 "5bcb8b3a095b302139c7be9593e9eea8d17b9df067df7d945b6a043fcbf7f65c"
      define_method(:install) do
        bin.install "bunkr"
      end
    end
  end

  def post_install
    system "/usr/bin/xattr", "-dr", "com.apple.quarantine", bin/"bunkr" if OS.mac?
  end

  test do
    system "#{bin}/bunkr", "--version"
  end
end
