# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bunkr < Formula
  desc "A fast, reliable downloader for Bunkr albums and files"
  homepage "https://github.com/yasithab/homebrew-taps"
  version "1.2.26"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yasithab/homebrew-taps/releases/download/v1.2.26/bunkr-1.2.26-darwin-amd64.tar.gz"
      sha256 "0a02985c9c8970157d8da60591ef2e08c1b5b00be2153bc8d00d3e6f6fe1358d"

      define_method(:install) do
        bin.install "bunkr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yasithab/homebrew-taps/releases/download/v1.2.26/bunkr-1.2.26-darwin-arm64.tar.gz"
      sha256 "10300d45275a0d0960fc1d1390f615bd0cf9fbd5652985d1111b513c30b81529"

      define_method(:install) do
        bin.install "bunkr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yasithab/homebrew-taps/releases/download/v1.2.26/bunkr-1.2.26-linux-amd64.tar.gz"
      sha256 "452bc8186be3edf1d73f685080b06d3cc5354740e9ea1fd715f4ca6e99645321"
      define_method(:install) do
        bin.install "bunkr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yasithab/homebrew-taps/releases/download/v1.2.26/bunkr-1.2.26-linux-arm64.tar.gz"
      sha256 "b661f8b9d837f93defe15a44cf6f9b8c14e58c8f637d424e691cee591985b544"
      define_method(:install) do
        bin.install "bunkr"
      end
    end
  end

  def post_install
    system "/usr/bin/xattr", "-dr", "com.apple.quarantine", bin/"bunkr" if OS.mac?
  end

  test do
    system "#{bin}/bunkr", "--version"
  end
end
