# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pbs < Formula
  desc "Pirate Bay torrent search CLI with JSON output and mirror fallback"
  homepage "https://github.com/yasithab/homebrew-taps"
  version "1.2.28"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yasithab/homebrew-taps/releases/download/v1.2.28/pbs-1.2.28-darwin-amd64.tar.gz"
      sha256 "dfb2aeb9a674979fb848afea4136224890ea156d0b476a18fdd80f403aa2975a"

      define_method(:install) do
        bin.install "pbs"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yasithab/homebrew-taps/releases/download/v1.2.28/pbs-1.2.28-darwin-arm64.tar.gz"
      sha256 "8f08b3cf6a632cd054e41a4cc0ac6b309ad1ba3a196e9cdac17bb208f4c7d249"

      define_method(:install) do
        bin.install "pbs"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yasithab/homebrew-taps/releases/download/v1.2.28/pbs-1.2.28-linux-amd64.tar.gz"
      sha256 "db2bfb1b4982a566fb2257801d64a67a50e6693128cda65d7dec11805b7a5cfd"
      define_method(:install) do
        bin.install "pbs"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yasithab/homebrew-taps/releases/download/v1.2.28/pbs-1.2.28-linux-arm64.tar.gz"
      sha256 "cc191e46701340b55d5201538e26bf6b21b859908b492d52939a53dec0dd10a6"
      define_method(:install) do
        bin.install "pbs"
      end
    end
  end

  def post_install
    system "/usr/bin/xattr", "-dr", "com.apple.quarantine", bin/"pbs" if OS.mac?
  end

  test do
    system "#{bin}/pbs", "--version"
  end
end
