# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ssm < Formula
  desc "A command-line tool for AWS SSM"
  homepage "https://github.com/yasithab/homebrew-taps"
  version "1.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yasithab/homebrew-taps/releases/download/v1.1.1/ssm-1.1.1-darwin-amd64.tar.gz"
      sha256 "aec1126b905d124699cfbf6597734584c2c5ff4e08886b7a3fe5e12d05858087"

      define_method(:install) do
        bin.install "ssm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yasithab/homebrew-taps/releases/download/v1.1.1/ssm-1.1.1-darwin-arm64.tar.gz"
      sha256 "7389827d75c607c4673f189c40c2d92028beba41587171f6bafcf1d71cf36dff"

      define_method(:install) do
        bin.install "ssm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yasithab/homebrew-taps/releases/download/v1.1.1/ssm-1.1.1-linux-amd64.tar.gz"
      sha256 "e5428ff6023702ee431320294250fa5cf80bf38428afeb5a2113ea8ed0a95af7"
      define_method(:install) do
        bin.install "ssm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yasithab/homebrew-taps/releases/download/v1.1.1/ssm-1.1.1-linux-arm64.tar.gz"
      sha256 "2dc01c013105f8c6eb6cc5f9f65dbe2ae1b469ac5911b5495a4b58e538bcd6c5"
      define_method(:install) do
        bin.install "ssm"
      end
    end
  end

  def post_install
    system "/usr/bin/xattr", "-dr", "com.apple.quarantine", bin/"ssm" if OS.mac?
  end

  test do
    system "#{bin}/ssm", "--version"
  end
end
