# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ssm < Formula
  desc "A command-line tool for AWS SSM"
  homepage "https://github.com/yasithab/homebrew-taps"
  version "1.2.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yasithab/homebrew-taps/releases/download/v1.2.2/ssm-1.2.2-darwin-amd64.tar.gz"
      sha256 "ca9706c4c76ee5d7fdee9a77eef95d23f96dbec0ad2215dd9143f143d70bc64c"

      define_method(:install) do
        bin.install "ssm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yasithab/homebrew-taps/releases/download/v1.2.2/ssm-1.2.2-darwin-arm64.tar.gz"
      sha256 "c2f6a00266461a60420d81badea30a9779d97a07c525faf29d726bef75a10e61"

      define_method(:install) do
        bin.install "ssm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yasithab/homebrew-taps/releases/download/v1.2.2/ssm-1.2.2-linux-amd64.tar.gz"
      sha256 "2311cb491ad54fb9e374d9b5eca0feb1ff0014418d14921be4d1418b0bf861f9"
      define_method(:install) do
        bin.install "ssm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yasithab/homebrew-taps/releases/download/v1.2.2/ssm-1.2.2-linux-arm64.tar.gz"
      sha256 "c65dcf2acae0b25f5d5a6be5cf9f3c78660f06f9066d9f0c0a8046c6d10b1ff5"
      define_method(:install) do
        bin.install "ssm"
      end
    end
  end

  def post_install
    system "/usr/bin/xattr", "-dr", "com.apple.quarantine", bin/"ssm" if OS.mac?
  end

  test do
    system "#{bin}/ssm", "--version"
  end
end
